### ISSUE TITLE
Share view event generation

### ISSUE THREAD

**Issue by yparitcher** [abe-101/myHebrewDates#13]
You might miss events in the share view, a leap year is 385 days > than 365 so you will miss hebrew events that just passed.

Maybe make a version of get_english_dates like get_next_english_date, that just returns the first match in hebrew_to_english_dict. Then make another function similar to generate_ical, that for each hebrew date, (gets the next english date?) And adds it to the list, and sorts the list.

**Comment by abe-101** [comment]
the shared view hows now been updated
its using a 3rd party js library to render a calendar with the events form teh ical feed
