### ISSUE TITLE
Calendar Edits Not Reflected When Adding to Google

### ISSUE THREAD

**Issue by YisroelTech** [abe-101/myHebrewDates#64]
Thanks for this awesome project!

I created this calendar https://myhebrewdates.com/calendars/33ff13d1-1145-49e7-8326-3187990ec385/ with the name **_Test Hebrew Date_** and one birthday, added it to my Google Calendar, then edited it (the name and added another birthday) but it didn't update on my Google Calendar (they're supposed to automatically be updated on the Google Calendar?)

Even when removed/unsubscribed, and even when added to another Google account's calendar, it seems to still add only the old name with one birthday.

Why doesn't it update?

![Animation](https://github.com/abe-101/myHebrewDates/assets/7387839/dfd9c121-024d-4df1-b273-556aea98fd79)

**Comment by abe-101** [comment]
Hey @YisroelTech ,

Thanks for the feedback!

About your Google Calendar issue: Google Calendar updates external calendars roughly every 12-24 hours. Plus, it caches events. This means even after deleting and re-adding, you might still see old data until the cache refreshes. Please allow some time for updates to reflect.

If you've waited and it's still not updated, drop a comment and we'll investigate further.

Cheers,
@abe-101

**Comment by YisroelTech** [comment]
Got it, I'll wait and report back.

(It was just odd to me that the cache is across Google, even for different account.)

Indeed, the ICS file in the Add To Calendar>Google button is properly up to date.

**Comment by abe-101** [comment]
yes
It seems that Google does indeed cache the content of a calendar feed across accounts

**Comment by abe-101** [comment]
I added a FAQ section on the about page answering this question
https://github.com/abe-101/myHebrewDates/pull/65

**Comment by YisroelTech** [comment]
And of course you were right, and it updated nicely (name of calendar as well as events) 🎉👍🏻.

And thanks for adding it to the FAQ.

A trick for a workaround (if someone can't wait... or is testing something and wants immediate effect) I saw [here](https://www.binarysludge.com/2012/02/01/how-to-force-refresh-google-calendar/) is to alter the calendar URL (can be after the _.ics_, so it doesn't actually affect the data) to something new (e.g. `https://calendar.google.com/calendar/r?cid=http%3A%2F%2Fmyhebrewdates.com/calendars/33ff13d1-1145-49e7-8326-3187990ec385.ics?1`.
